# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Clone web repo
      run: git clone https://github.com/Jeevan-Kishore/konnect-web.git
    - name: Check files
      run: ls -la
    - name: Remove existing files
      working-directory: ./konnect-web
      run: rm -rf ./*
    - name: Copy files to repo
      run: cp -r ./build/* ./konnect-web/
    - name: Commit files
      working-directory: ./konnect-web
      run: |
        git init
        git config --local --unset-all "http.https://github.com/.extraheader"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote -v
        git remote set-url origin https://github.com/Jeevan-Kishore/konnect-web.git
        git remote -v
        git add . -f
        git status
        git commit -m "Add build changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        repository: "Jeevan-Kishore/konnect-web"
        branch: "master"
        directory: "./konnect-web"
